name : Python CI

on:
 push:
   branches: ["main"]
 pull_request:
   branches: ["main"]

jobs:
  build:


     runs-on: unbantu-latest

     steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up Python
       uses: sctions/setup-python@v5
       with:
         python-version: '3.10'

     - name: Install dependencies
       run:
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -requirements.txt; fi
     - name: Run tests
       run:
         if [ -d tests ]; then pytest -q else echo "No tests directory found"; fi

     - name: Lint (optional)
       run: |
        pip install flake
        flake8 . || true

     - name: Build success
       run: echo "Build completedsuccessfully"
     
  
